package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* miércoles 1 de marzo de 2023 19H02' CET
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float mul (float a, float b);
  float sub (float a, float b);
  CalcApp.Complex complexSum (CalcApp.Complex a, CalcApp.Complex b);
  CalcApp.Complex complexSub (CalcApp.Complex a, CalcApp.Complex b);
} // interface CalcOperations
