package CalcApp;


/**
* CalcApp/Complex.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* miércoles 1 de marzo de 2023 19H02' CET
*/

public final class Complex implements org.omg.CORBA.portable.IDLEntity
{
  public float real = (float)0;
  public float imaginary = (float)0;

  public Complex ()
  {
  } // ctor

  public Complex (float _real, float _imaginary)
  {
    real = _real;
    imaginary = _imaginary;
  } // ctor

} // class Complex
